name: RandomTeleport
version: 1.0
description: Plugin perfecto para evitar el abuso en pvp

author: Julito
main: es.jlh.randomTeleport.plugin.RandomTeleport

commands:
    rt:
        usage: /<command>
        aliases: [randomteleport]
        description: Autor del plugin
        permission: rt.author
    rtconfig:
        usage: /<command> <nombre_zona>
        aliases: [rtcrea]
        description: Configurar el plugin
        permission: rt.config
    rtpurge:
        usage: /<command>
        aliases: [rtpurga]
        description: Limpia el historial de las zonas no activas
        permission: rt.purge
    rtreload:
        usage: /<command>
        description: Recarga el plugin
        permission: rt.reload
    rtzone:
        usage: /<command> <activar/borrar/ver/lista> [nombre_zona] [tiempo]
        aliases: [rtzona]
        description: Crea, elimina, muestra o lista las zonas activas
        permission: rt.zone  
        
permissions:
   rt.*:
     description: Consigue acceso a todos los comandos de RandomTeleport
     children:
       rt.author: true
       rt.config: true
       rt.zona: true
       rt.purge: true       
       rt.reload: true       
   rt.author:
     description: Muestra el autor
     default: true
   rt.config:
     description: Configura el plugin
     default: OP
   rt.zone:
     description: Operaciones con las zonas
     default: OP
   rt.purge:
     description: Limpia la configuracion
     default: OP
   rt.reload:
     description: Recarga el plugin
     default: OP     