name: RandomTeleport
version: 1.0
description: Plugin perfecto para evitar el abuso en pvp

author: Julito
authors: [Tyr, Eos] 

main: es.jlh.randomTeleport.plugin.RandomTeleport

commands:
    rt:
        usage: /<command>
        description: Autor del plugin
    rtconfig:
        usage: /<command>
        aliases: [rtconf]
        description: Configurar el plugin
        permission: rt.config
    rtreload:
        usage: /<command>
        aliases: [rtrel]
        description: Recarga el plugin
        permission: rt.reload

permissions:
   rt.*:
     description: Consigue acceso a todos los comandos de RandomTeleport
     children:
       rt.reload: true
       rt.config: true
   rt.reload:
     description: Recarga el plugin
     default: false
   rt.config:
     description: Configura el plugin
     default: false